package com.qunniox.airlines.controller;

import java.util.List;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.qunniox.airlines.entities.Airport;
import com.qunniox.airlines.services.AirportService;

@RestController
@RequestMapping //// This means URL's start 

@CrossOrigin(origins="*",allowedHeaders="*")
@Transactional

public class AirportController {     //This means to get the bean called userRepository, Which is auto-generated by Spring, we will use it to handle the data
	
	@Autowired
	AirportService airportService;

	@GetMapping("/viewAirport/{id}")
	public Airport viewAirport(@PathVariable("id") String airportCode) {
		return airportService.viewAirport(airportCode);
	}

	@GetMapping("/allAirport")
	public Iterable<Airport> viewAllAirport() {
		return airportService.viewAllAirport();
	}

	@PostMapping("/addAirport")
	public void addAirport(@RequestBody Airport airport)
	{
		airportService.addAirport(airport);
	}

	@PutMapping("/updateAirport/{id}")
	public void modifyAirport (@PathVariable ("id") String airportCode ,@RequestBody Airport airport) {
		airport.setAirportCode(airportCode);
		airportService.modifyAirport(airport);
	}

	@DeleteMapping("/deleteAirport/{id}")
	public void removeAirport(@PathVariable("id") String airportCode) {
		airportService.removeAirport(airportCode);
	}

}